# Generated by Django 3.1.6 on 2021-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
    ]
